### ISSUE TITLE
Use only 4KB and 2MB pages.

### ISSUE THREAD

**Issue by akshaybaviskar** [technion-csl/mosalloc#1]
Hello,

Is there a way that I assign a layout with only 4 KB and 2 MB pages? and not use 1GB pages?
I have Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz with 250 GB RAM divided on two NUMA nodes.

Most of the allocations with 1GB are resulting in the following error:

> "Error: could not reserve the requested number of huge pages;
> Please reboot the system and try again"

I tried to manually allocate the pages which the script was trying to do and found that I am able to allocate 2MB pages but it's failing for 1 GB page allocations.

Also, I see that in the paper you have used only 2MB and 4 KB pages to generate 54 sample points.
So, I would be fine to use only 2MB and 4 KB combinations.

I want to know if there is an easy way to disable it, say by a parameter or by editing some file?
I tried removing layout1GB line from experiments/single_page_size/layouts.txt, but it didn't work.

Thanks,
Akshay

**Comment by magbarya** [comment]
Fixed the issue by skipping reserving an additional hugepage when the Mosalloc pools use no hugepages.
[56a7075](https://github.com/technion-csl/mosalloc/commit/56a7075eb96570be9785a09e83413978cc953ad6)

**Comment by idanyani** [comment]
@akshaybaviskar: thanks for catching this bug!
And @magbarya: thanks for fixing this bug!

It would be interesting to understand why @akshaybaviskar couldn't allocate 1GB hugepages because 250GB of RAM should be more than enough. Perhaps your memory is highly fragmented? Please follow the hint in the error message ("Please reboot the system and try again") and rerun the script. A "fresh" system is much less likely to suffer from fragmentation.
